FROM signoz/signoz-otel-collector:v0.144.3

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/signoz-otel-collector migrate bootstrap && /signoz-otel-collector migrate sync up && /signoz-otel-collector migrate async up && echo 'All migrations complete. Idling.' && tail -f /dev/null"]
